import '@twitter-web/ui/styles.css';
import { ThemeProvider } from '@twitter-web/ui';

export const metadata = {
  title: 'Welcome to x-desktop',
  description: 'Generated by create-nx-workspace',
  icons: {
    icon: '/logo-x.svg',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white text-black dark:bg-dark-1 dark:text-white min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
