import '@twitter-web/ui/styles.css';
import { Sidebar } from '~/components/sidebar';

export const metadata = {
  title: 'Welcome to x-desktop',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white text-black dark:bg-dark-1 dark:text-white min-h-screen">
        <div className="flex max-w-7xl justify-between mx-auto min-h-screen">
          <header className="max-h-screen overflow-y-scroll sticky top-0">
            <Sidebar />
          </header>

          <main className="max-h-screen flex justify-start grow border-l border-dark-4">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
